// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
// VirtualKey.h
#pragma once

// ----------------------------------------------------------------------------
enum EVirtualKey
{
	VK_Null,
	VK_Esc,
	VK_Tab,
	VK_Enter,
	VK_Backspace,
	VK_LeftControl,
	VK_LeftShift,
	VK_LeftAlt,
	VK_RightControl,
	VK_RightShift,
	VK_RightAlt,
	VK_Space = 0x20,
	VK_Apostrophe = 0x27,
	VK_Comma = 0x2C,
	VK_Minus = 0x2D,
	VK_Dot = 0x2E,
	VK_Slash = 0x2F,
	VK_Equal = 0x3D,
	VK_0 = 0x30,
	VK_1 = 0x31,
	VK_2 = 0x32,
	VK_3 = 0x33,
	VK_4 = 0x34,
	VK_5 = 0x35,
	VK_6 = 0x36,
	VK_7 = 0x37,
	VK_8 = 0x38,
	VK_9 = 0x39,
	VK_Semicolon = 0x3B,
	VK_A = 0x41,
	VK_B = 0x42,
	VK_C = 0x43,
	VK_D = 0x44,
	VK_E = 0x45,
	VK_F = 0x46,
	VK_G = 0x47,
	VK_H = 0x48,
	VK_I = 0x49,
	VK_J = 0x4A,
	VK_K = 0x4B,
	VK_L = 0x4C,
	VK_M = 0x4D,
	VK_N = 0x4E,
	VK_O = 0x4F,
	VK_P = 0x50,
	VK_Q = 0x51,
	VK_R = 0x52,
	VK_S = 0x53,
	VK_T = 0x54,
	VK_U = 0x55,
	VK_V = 0x56,
	VK_W = 0x57,
	VK_X = 0x58,
	VK_Y = 0x59,
	VK_Z = 0x5A,
	VK_LeftBracket = 0x5B,
	VK_Backslash = 0x5C,
	VK_RightBracket = 0x5D,
	VK_GraveAccent = 0x60,
	VK_NumLock,
	VK_CapsLock,
	VK_ScrollLock,	
	VK_F1,
	VK_F2,
	VK_F3,
	VK_F4,
	VK_F5,
	VK_F6,
	VK_F7,	
	VK_F8,	
	VK_F9,	
	VK_F10,	
	VK_F11,
	VK_F12,
	VK_Num0,
	VK_Num1,
	VK_Num2,
	VK_Num3,
	VK_Num4,
	VK_Num5,
	VK_Num6,
	VK_Num7,
	VK_Num8,
	VK_Num9,
	VK_NumSlash,
	VK_NumAsterisk,
	VK_NumMinus,
	VK_NumPlus,
	VK_NumEnter,
	VK_NumDel,

	VK_GreyUp,
	VK_GreyLeft,
	VK_GreyDown,
	VK_GreyRight,

	VK_GreyInsert,
	VK_GreyDelete,
	VK_GreyHome,
	VK_GreyEnd,
	VK_GreyPageUp,
	VK_GreyPageDown,
		
	VK_LeftWindow,
	VK_RightWindow,
	VK_Menu,
		
	VK_Pause,
	VK_PrintScreen
};
// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=